In [5]:
import numpy as np
import pandas as pd
from pathlib import Path

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.4.6
Pandas: 3.0.5

In [6]:
DATA_PATH = Path("../data/raw/WEC_Simulation_Data.csv")

df = pd.read_csv(DATA_PATH)

print("Dataset shape:", df.shape)

Dataset shape: (450900, 19)

In [7]:
print(df.columns.tolist())
df.head()

['l1', 'd1', 'd2', 'a1', 'm1', 'Qi', 'w1', 'w2', 'B', 'P_ext', 'eta_maxx', 'P_ext_plate', 'P_ext_rel_error', 'xi1_rms', 'xi2_rms', 'REFL', 'TRANS', 'chi', 'P_inc']

,l1,d1,d2,a1,m1,Qi,w1,w2,B,P_ext,eta_maxx,P_ext_plate,P_ext_rel_error,xi1_rms,xi2_rms,REFL,TRANS,chi,P_inc
0,10,1.0,1.5,0.0,1,4.00,0.148368,0.148368,10.296736,121.429417,0.007275,669.850584,4.516378,0.895059,0.867017,0.006090,0.986635,1.058575,16691.239305
1,10,1.0,1.5,0.0,1,4.01,0.148368,0.148368,10.296736,131.331285,0.007842,700.988869,4.337562,0.903243,0.876980,0.006239,0.985919,1.058736,16747.518448
2,10,1.0,1.5,0.0,1,4.02,0.148368,0.148368,10.296736,142.341292,0.008471,736.552365,4.174552,0.912409,0.888063,0.006384,0.985146,1.058887,16803.960161
3,10,1.0,1.5,0.0,1,4.03,0.148368,0.148368,10.296736,154.619917,0.009171,777.194664,4.026485,0.922690,0.900410,0.006526,0.984304,1.059028,16860.562837
4,10,1.0,1.5,0.0,1,4.04,0.148368,0.148368,10.296736,168.359488,0.009952,823.701151,3.892514,0.934241,0.914187,0.006665,0.983383,1.059159,16917.324821

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 450900 entries, 0 to 450899
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   l1               450900 non-null  int64
 1   d1               450900 non-null  float64
 2   d2               450900 non-null  float64
 3   a1               450900 non-null  float64
 4   m1               450900 non-null  int64
 5   Qi               450900 non-null  float64
 6   w1               450900 non-null  float64
 7   w2               450900 non-null  float64
 8   B                450900 non-null  float64
 9   P_ext            450900 non-null  float64
 10  eta_maxx         450900 non-null  float64
 11  P_ext_plate      450900 non-null  float64
 12  P_ext_rel_error  450900 non-null  float64
 13  xi1_rms          450900 non-null  float64
 14  xi2_rms          450900 non-null  float64
 15  REFL             450900 non-null  float64
 16  TRANS            450900 non-null  float64
 17  chi              450900 non-null  float64
 18  P_inc            450900 non-null  float64
dtypes: float64(17), int64(2)
memory usage: 65.4 MB

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
l1,450900.0,2.000000e+01,7.071076e+00,1.000000e+01,15.000000,20.000000,25.000000,3.000000e+01
d1,450900.0,1.500000e+00,4.082487e-01,1.000000e+00,1.000000,1.500000,2.000000,2.000000e+00
d2,450900.0,2.000000e+00,4.082487e-01,1.500000e+00,1.500000,2.000000,2.500000,2.500000e+00
a1,450900.0,7.500000e-01,5.590176e-01,0.000000e+00,0.375000,0.750000,1.125000,1.500000e+00
m1,450900.0,3.000000e+00,1.414215e+00,1.000000e+00,2.000000,3.000000,4.000000,5.000000e+00
Qi,450900.0,6.500000e+00,1.446261e+00,4.000000e+00,5.250000,6.500000,7.750000,9.000000e+00
w1,450900.0,1.396405e-01,7.126008e-03,1.309130e-01,0.130913,0.139641,0.148368,1.483681e-01
w2,450900.0,1.396405e-01,7.126008e-03,1.309130e-01,0.130913,0.139641,0.148368,1.483681e-01
B,450900.0,2.027928e+01,7.071090e+00,1.026183e+01,15.261826,20.279281,25.296736,3.029674e+01
P_ext,450900.0,-3.638102e+03,4.638044e+05,-1.121170e+08,30.036216,125.804144,471.650698,1.515276e+04
eta_maxx,450900.0,-9.864046e-02,1.249542e+01,-3.020097e+03,0.000890,0.004339,0.017569,4.175419e-01
P_ext_plate,450900.0,1.308594e+06,1.621486e+08,1.326076e+02,547.152771,2043.943892,17719.605604,3.916689e+10
P_ext_rel_error,450900.0,1.417150e+02,6.347425e+03,2.394196e+00,3.544553,4.887162,34.706241,3.296735e+06
xi1_rms,450900.0,4.185829e+00,5.865548e+01,6.515739e-01,1.030743,1.348464,2.969623,1.029642e+04
xi2_rms,450900.0,4.542773e+00,5.888341e+01,5.471573e-01,0.933298,1.333986,3.517318,1.033227e+04
REFL,450900.0,1.420731e-01,5.988682e+00,1.714521e-08,0.001105,0.002934,0.123686,1.444681e+03
TRANS,450900.0,9.565673e-01,6.512905e+00,5.030512e-03,0.859107,0.983071,0.995238,1.576416e+03
chi,450900.0,9.845280e-01,4.564631e-02,9.222071e-01,0.942743,0.975713,1.026316,1.059984e+00
P_inc,450900.0,2.971069e+04,6.563804e+03,1.669124e+04,24291.607844,30870.549773,35569.226447,3.883190e+04

In [10]:
missing = df.isnull().sum()

print(missing)

l1                 0
d1                 0
d2                 0
a1                 0
m1                 0
Qi                 0
w1                 0
w2                 0
B                  0
P_ext              0
eta_maxx           0
P_ext_plate        0
P_ext_rel_error    0
xi1_rms            0
xi2_rms            0
REFL               0
TRANS              0
chi                0
P_inc              0
dtype: int64

In [11]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 0

In [12]:
FEATURES = [
    "l1",
    "d1",
    "d2",
    "a1",
    "m1",
    "Qi"
]

TARGET = "P_ext"

X = df[FEATURES].copy()
y = df[TARGET].copy()

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   l1   d1   d2   a1  m1    Qi
0  10  1.0  1.5  0.0   1  4.00
1  10  1.0  1.5  0.0   1  4.01
2  10  1.0  1.5  0.0   1  4.02
3  10  1.0  1.5  0.0   1  4.03
4  10  1.0  1.5  0.0   1  4.04

Target:
0    121.429417
1    131.331285
2    142.341292
3    154.619917
4    168.359488
Name: P_ext, dtype: float64

In [13]:
X.describe().T

       count   mean       std   min     25%    50%     75%   max
l1  450900.0  20.00  7.071076  10.0  15.000  20.00  25.000  30.0
d1  450900.0   1.50  0.408249   1.0   1.000   1.50   2.000   2.0
d2  450900.0   2.00  0.408249   1.5   1.500   2.00   2.500   2.5
a1  450900.0   0.75  0.559018   0.0   0.375   0.75   1.125   1.5
m1  450900.0   3.00  1.414215   1.0   2.000   3.00   4.000   5.0
Qi  450900.0   6.50  1.446261   4.0   5.250   6.50   7.750   9.0

In [14]:
y.describe()

count    4.509000e+05
mean    -3.638102e+03
std      4.638044e+05
min     -1.121170e+08
25%      3.003622e+01
50%      1.258041e+02
75%      4.716507e+02
max      1.515276e+04
Name: P_ext, dtype: float64

In [15]:
print("Minimum P_ext:", y.min())
print("Maximum P_ext:", y.max())
print("Mean P_ext:", y.mean())
print("Median P_ext:", y.median())

Minimum P_ext: -112117019.928368
Maximum P_ext: 15152.7597816109
Mean P_ext: -3638.1024564209574
Median P_ext: 125.80414414577601

In [16]:
print("Negative P_ext:", (y < 0).sum())
print("Zero P_ext:", (y == 0).sum())
print("NaN P_ext:", y.isna().sum())
print("Infinite P_ext:", np.isinf(y).sum())

Negative P_ext: 87539
Zero P_ext: 0
NaN P_ext: 0
Infinite P_ext: 0